import { Patient, Hospital, Staff, ConsentGrant, AccessEvent, MedicalRecord, Prescription, HealthTrendSnapshot, AccessAnomalyAlert, BlockchainBlock } from '../types';

export const INITIAL_PATIENT: Patient = {
  id: 'p-101',
  healthId: 'HL-1894-4321',
  name: 'Olivia Chen',
  dob: '1992-04-14',
  gender: 'Female',
  email: 'olivia.chen@healthlink.org',
  phone: '+1 (555) 438-9210',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  emergencyProfile: {
    bloodGroup: 'A+',
    allergies: ['Penicillin', 'Sulfa Drugs', 'Latex (Mild)'],
    criticalMeds: ['Lisinopril 10mg (Daily)', 'Albuterol Inhaler (PRN)'],
    criticalConditions: ['Hypertension Stage 1', 'Mild Exercise-Induced Asthma'],
    organDonor: true,
    dnrStatus: false,
    emergencyContacts: [
      {
        name: 'David Chen',
        relation: 'Spouse',
        phone: '+1 (555) 892-3401',
        isPrimary: true,
      },
      {
        name: 'Grace Lin',
        relation: 'Mother',
        phone: '+1 (555) 741-2099',
        isPrimary: false,
      },
    ],
  },
  registeredBiometrics: {
    faceTemplateRef: 'sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    faceRegisteredAt: '2025-11-10T14:32:00Z',
    fingerprintTemplateRef: 'fido2:credential:0x98f24a61c71b489d',
    fingerprintRegisteredAt: '2025-11-10T14:35:00Z',
    qrCodeString: 'HEALLOCK:EMERGENCY:HL-1894-4321:PUB_KEY_0x7b2f',
  },
};

export const INITIAL_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-001',
    name: 'City Care Hospital',
    code: 'CCH-METRO',
    city: 'New York',
    verificationStatus: 'verified',
    registeredDepartments: ['Cardiology', 'Internal Medicine', 'Emergency Trauma', 'Radiology'],
    publicKey: '0x04f128c9b8823194a283e1c98a28f88c91a384b72183e8b',
  },
  {
    id: 'hosp-002',
    name: 'Apex Diagnostics & Imaging',
    code: 'APEX-DIAG',
    city: 'Brooklyn',
    verificationStatus: 'verified',
    registeredDepartments: ['Pathology', 'MRI & CT Radiology', 'Hematology'],
    publicKey: '0x0473919c01726a117b399281ca823901726481bbca38',
  },
  {
    id: 'hosp-003',
    name: 'Metro Health Emergency Trauma Center',
    code: 'METRO-ER',
    city: 'Manhattan',
    verificationStatus: 'verified',
    registeredDepartments: ['Level 1 Trauma', 'Resuscitation Unit', 'Critical Care'],
    publicKey: '0x04e1293bb8112398418ab183719bca182391bba108',
  },
  {
    id: 'hosp-004',
    name: 'St. Jude Community Clinic',
    code: 'STJUDE-CLINIC',
    city: 'Queens',
    verificationStatus: 'pending',
    registeredDepartments: ['Family Medicine', 'Outpatient'],
    publicKey: '0x04928174ba10293817ab128471928371829371089',
  },
];

export const INITIAL_STAFF: Staff[] = [
  {
    id: 'staff-dr-sharma',
    hospitalId: 'hosp-001',
    hospitalName: 'City Care Hospital',
    name: 'Dr. Rajesh Sharma, MD',
    role: 'doctor',
    department: 'Internal Medicine & Cardiology',
    badgeNumber: 'MD-84910',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'staff-er-vance',
    hospitalId: 'hosp-003',
    hospitalName: 'Metro Health Trauma Center',
    name: 'Dr. Elena Vance, MD',
    role: 'emergency',
    department: 'Emergency & Resuscitation',
    badgeNumber: 'ER-49102',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813628-9844445c7198?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'staff-pharm-croft',
    hospitalId: 'hosp-001',
    hospitalName: 'City Care Hospital',
    name: 'Marcus Croft, PharmD',
    role: 'pharmacist',
    department: 'Hospital Pharmacy',
    badgeNumber: 'PH-19401',
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'staff-admin-dave',
    hospitalId: 'hosp-001',
    hospitalName: 'City Care Hospital',
    name: 'David Reynolds',
    role: 'admin',
    department: 'Cybersecurity & Compliance',
    badgeNumber: 'SEC-0091',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'staff-recep-sarah',
    hospitalId: 'hosp-001',
    hospitalName: 'City Care Hospital',
    name: 'Sarah Jenkins',
    role: 'receptionist',
    department: 'Patient Admissions',
    badgeNumber: 'REC-3012',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_CONSENTS: ConsentGrant[] = [
  {
    id: 'c-001',
    patientId: 'p-101',
    hospitalId: 'hosp-001',
    hospitalName: 'City Care Hospital',
    scope: ['Lab Reports', 'Rx History'],
    grantedAt: '2026-01-15T09:00:00Z',
    expiresAt: '2026-10-31T23:59:59Z',
    status: 'active',
  },
  {
    id: 'c-002',
    patientId: 'p-101',
    hospitalId: 'hosp-002',
    hospitalName: 'Apex Diagnostics & Imaging',
    scope: ['Diagnostic Scans', 'Lab Reports'],
    grantedAt: '2026-03-01T10:00:00Z',
    expiresAt: '2026-12-31T23:59:59Z',
    status: 'active',
  },
  {
    id: 'c-003',
    patientId: 'p-101',
    hospitalId: 'hosp-004',
    hospitalName: 'St. Jude Community Clinic',
    scope: ['Rx History'],
    grantedAt: '2025-05-10T12:00:00Z',
    expiresAt: '2025-11-10T12:00:00Z',
    status: 'expired',
  },
];

export const INITIAL_ACCESS_EVENTS: AccessEvent[] = [
  {
    id: 'tx-001',
    patientId: 'p-101',
    patientName: 'Olivia Chen',
    hospitalId: 'hosp-001',
    hospitalName: 'City Care Hospital (Dr. Sharma)',
    staffId: 'staff-dr-sharma',
    staffName: 'Dr. Rajesh Sharma',
    staffRole: 'Doctor',
    accessType: 'normal',
    action: 'Read Lab Reports',
    reason: 'Follow-up consultation for BP management',
    timestamp: '10:14 AM · Oct 24, 2026',
    txHash: '0x4f8a9271c39048a1d7462bb1e892c9071b62391054a3',
    blockNumber: 48912,
    verified: true,
  },
  {
    id: 'tx-002',
    patientId: 'p-101',
    patientName: 'Olivia Chen',
    hospitalId: 'hosp-002',
    hospitalName: 'Apex Diagnostics (Staff ID 421)',
    staffId: 'staff-apex-421',
    staffName: 'Lab Tech Marcus',
    staffRole: 'Technician',
    accessType: 'normal',
    action: 'Uploaded CBC Lab Panel',
    reason: 'Diagnostic test completion upload',
    timestamp: '3:30 PM · Oct 22, 2026',
    txHash: '0x8b12f491c981a44e7829103cba281744920418373e41',
    blockNumber: 48805,
    verified: true,
  },
  {
    id: 'tx-003',
    patientId: 'p-101',
    patientName: 'Olivia Chen',
    hospitalId: 'hosp-001',
    hospitalName: 'City Care Hospital (Dr. Sharma)',
    staffId: 'staff-dr-sharma',
    staffName: 'Dr. Rajesh Sharma',
    staffRole: 'Doctor',
    accessType: 'normal',
    action: 'Prescribed Lisinopril 10mg',
    reason: 'Routine quarterly Rx refill and AI Safety verification',
    timestamp: '11:05 AM · Sep 18, 2026',
    txHash: '0x3c990a18274b62f1a94820dc82374618293746194b72',
    blockNumber: 47920,
    verified: true,
  },
  {
    id: 'tx-004',
    patientId: 'p-101',
    patientName: 'Olivia Chen',
    hospitalId: 'hosp-003',
    hospitalName: 'Metro Health Emergency Trauma',
    staffId: 'staff-er-vance',
    staffName: 'Dr. Elena Vance',
    staffRole: 'Emergency Staff',
    accessType: 'emergency',
    factorUsed: 'face',
    action: 'Emergency Profile Unlocked',
    reason: 'Trauma / Road Incident — Patient Unconscious',
    timestamp: '02:15 AM · Jul 12, 2026',
    txHash: '0x9d4a187263b190ca84729101238b17482910384799c2',
    blockNumber: 45100,
    verified: true,
  },
];

export const INITIAL_RECORDS: MedicalRecord[] = [
  {
    id: 'rec-001',
    patientId: 'p-101',
    category: 'Lab Reports',
    title: 'Comprehensive Metabolic & Lipid Panel',
    date: '2026-10-22',
    hospitalName: 'Apex Diagnostics & Imaging',
    doctorName: 'Dr. Rajesh Sharma',
    fileType: 'PDF / OCR Analyzed',
    isEncrypted: true,
    contentEncrypted: 'U2FsdGVkX1+9Kx2Wv83...[AES-256-GCM 256-bit Key Encrypted off-chain]',
    aiExtractedFields: {
      medications: ['Lisinopril 10mg'],
      values: {
        'Total Cholesterol': '182 mg/dL (Normal)',
        'HDL': '58 mg/dL (Optimal)',
        'LDL': '104 mg/dL (Desirable)',
        'Triglycerides': '110 mg/dL (Normal)',
        'Fasting Glucose': '91 mg/dL (Normal)',
        'eGFR': '> 90 mL/min (Healthy)',
      },
      diagnoses: ['Normal Lipid Profile', 'Optimal Kidney Function'],
      keyFindings: [
        'Cholesterol reduced 12% compared to previous 6-month panel.',
        'Renal filtration rate optimal with current Lisinopril dosage.',
      ],
      summary: 'Biomarkers are well within reference ranges. No electrolyte imbalances observed.',
      confidenceScore: 0.98,
    },
  },
  {
    id: 'rec-002',
    patientId: 'p-101',
    category: 'Lab Reports',
    title: 'Complete Blood Count (CBC) with Differential',
    date: '2026-08-15',
    hospitalName: 'City Care Hospital',
    doctorName: 'Dr. Rajesh Sharma',
    fileType: 'PDF / OCR Analyzed',
    isEncrypted: true,
    contentEncrypted: 'U2FsdGVkX18921Jka...[AES-256-GCM 256-bit Key Encrypted off-chain]',
    aiExtractedFields: {
      values: {
        'WBC': '6.4 x10^3/uL (Normal)',
        'RBC': '4.55 x10^6/uL (Normal)',
        'Hemoglobin': '13.8 g/dL (Normal)',
        'Platelets': '245 x10^3/uL (Normal)',
      },
      diagnoses: ['Normal Hemogram'],
      summary: 'All leukocyte and erythrocyte indices are within standard reference intervals.',
      confidenceScore: 0.99,
    },
  },
  {
    id: 'rec-003',
    patientId: 'p-101',
    category: 'Lab Reports',
    title: 'HbA1c Glycemic Assessment',
    date: '2026-05-10',
    hospitalName: 'Apex Diagnostics & Imaging',
    doctorName: 'Dr. Rajesh Sharma',
    fileType: 'PDF / OCR Analyzed',
    isEncrypted: true,
    contentEncrypted: 'U2FsdGVkX19428Jk...[AES-256-GCM 256-bit Key Encrypted off-chain]',
    aiExtractedFields: {
      values: {
        'HbA1c': '5.3% (Non-diabetic range < 5.7%)',
      },
      diagnoses: ['Normal Glycemic Control'],
      summary: 'Glycated hemoglobin indicates normal glucose regulation across preceding 90 days.',
      confidenceScore: 0.99,
    },
  },
  {
    id: 'rec-004',
    patientId: 'p-101',
    category: 'Prescriptions',
    title: 'Hypertension & Bronchodilator Maintenance Rx',
    date: '2026-09-18',
    hospitalName: 'City Care Hospital',
    doctorName: 'Dr. Rajesh Sharma',
    fileType: 'Digital e-Prescription',
    isEncrypted: true,
    contentEncrypted: 'U2FsdGVkX17361Ka...[AES-256-GCM 256-bit Key Encrypted off-chain]',
    aiExtractedFields: {
      medications: ['Lisinopril 10mg Tab', 'Albuterol Sulfate 90mcg Inhalation Aerosol'],
      diagnoses: ['Primary Essential Hypertension', 'Mild Exercise-induced Bronchospasm'],
      keyFindings: [
        'Checked against Penicillin allergy: SAFE (No beta-lactam interaction)',
        'Checked against Sulfa allergy: SAFE (No sulfonamide moiety)',
      ],
      summary: 'Active maintenance therapy for BP control and PRN respiratory comfort.',
      confidenceScore: 1.0,
    },
  },
  {
    id: 'rec-005',
    patientId: 'p-101',
    category: 'Diagnostic Scans',
    title: '12-Lead Electrocardiogram (ECG) Report',
    date: '2026-06-12',
    hospitalName: 'Apex Diagnostics & Imaging',
    doctorName: 'Dr. Rajesh Sharma',
    fileType: 'DICOM Scanned ECG',
    isEncrypted: true,
    contentEncrypted: 'U2FsdGVkX100129K...[AES-256-GCM 256-bit Key Encrypted off-chain]',
    aiExtractedFields: {
      values: {
        'Heart Rate': '68 bpm (Normal Sinus Rhythm)',
        'PR Interval': '152 ms (Normal)',
        'QRS Duration': '86 ms (Normal)',
        'QTc': '412 ms (Normal)',
      },
      diagnoses: ['Normal Sinus Rhythm', 'No Ischemic ST/T changes'],
      summary: 'Normal cardiac rhythm and electrical conduction. No signs of hypertrophy or ischemia.',
      confidenceScore: 0.97,
    },
  },
  {
    id: 'rec-006',
    patientId: 'p-101',
    category: 'Diagnostic Scans',
    title: 'High-Resolution Chest Radiograph (PA View)',
    date: '2025-11-20',
    hospitalName: 'Apex Diagnostics & Imaging',
    doctorName: 'Dr. Rajesh Sharma',
    fileType: 'DICOM Scanned Image',
    isEncrypted: true,
    contentEncrypted: 'U2FsdGVkX174910P...[AES-256-GCM 256-bit Key Encrypted off-chain]',
    aiExtractedFields: {
      diagnoses: ['Clear Lung Fields', 'Normal Cardiothoracic Ratio'],
      keyFindings: [
        'Lungs are hyperinflated without focal consolidation or pneumothorax.',
        'Cardiac silhouette and mediastinal contours within normal limits.',
      ],
      summary: 'Clear respiratory parenchyma without acute pathology.',
      confidenceScore: 0.96,
    },
  },
];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx-001',
    patientId: 'p-101',
    hospitalId: 'hosp-001',
    hospitalName: 'City Care Hospital',
    doctorId: 'staff-dr-sharma',
    doctorName: 'Dr. Rajesh Sharma, MD',
    date: '2026-09-18',
    status: 'active',
    medications: [
      {
        name: 'Lisinopril',
        dosage: '10 mg',
        frequency: 'Once daily (Morning)',
        duration: '90 days (Refills: 2)',
        instructions: 'Take with or without food. Monitor blood pressure periodically.',
      },
      {
        name: 'Albuterol Inhaler (ProAir HFA)',
        dosage: '90 mcg/actuation',
        frequency: '1-2 puffs every 4-6 hrs PRN',
        duration: 'As needed',
        instructions: 'Inhale 15 minutes before vigorous exercise or during sudden wheezing.',
      },
    ],
    aiFlags: [
      {
        conflictType: 'safe',
        severity: 'safe',
        explanation: 'Claude AI and RxNorm cross-referenced with patient allergies (Penicillin, Sulfa) and drug database: No contraindications or interaction flags detected.',
        clinicalRecommendation: 'Safe to dispense. Continue routine BP monitoring.',
      },
    ],
  },
  {
    id: 'rx-002',
    patientId: 'p-101',
    hospitalId: 'hosp-001',
    hospitalName: 'City Care Hospital',
    doctorId: 'staff-dr-sharma',
    doctorName: 'Dr. Rajesh Sharma, MD',
    date: '2026-06-10',
    status: 'dispensed',
    medications: [
      {
        name: 'Cetirizine HCl',
        dosage: '10 mg',
        frequency: 'Once daily (Evening)',
        duration: '30 days',
        instructions: 'For seasonal allergic rhinitis. Non-drowsy formulation.',
      },
    ],
    aiFlags: [
      {
        conflictType: 'safe',
        severity: 'safe',
        explanation: 'Safe profile confirmed. No cross-reactivity with documented beta-lactam allergies.',
        clinicalRecommendation: 'Dispensed successfully by Hospital Dispensary.',
      },
    ],
  },
  {
    id: 'rx-003',
    patientId: 'p-101',
    hospitalId: 'hosp-002',
    hospitalName: 'Apex Diagnostics & Imaging',
    doctorId: 'staff-apex-421',
    doctorName: 'Dr. Gregory House, MD',
    date: '2026-04-12',
    status: 'flagged',
    medications: [
      {
        name: 'Spironolactone',
        dosage: '25 mg',
        frequency: 'Once daily',
        duration: '30 days',
        instructions: 'Adjunctive diuretic therapy.',
      },
    ],
    aiFlags: [
      {
        conflictType: 'drug_interaction',
        severity: 'warning',
        drugA: 'Spironolactone',
        drugB: 'Lisinopril',
        explanation: 'CLINICAL DDInter FLAG (WARNING): Spironolactone + Lisinopril. Concomitant administration significantly elevates hyperkalemia risk.',
        clinicalRecommendation: 'Monitor serum potassium and renal function closely.',
      },
    ],
  },
];

export const INITIAL_TRENDS: HealthTrendSnapshot[] = [
  {
    id: 'trend-bp',
    patientId: 'p-101',
    metricName: 'Blood Pressure (Systolic)',
    unit: 'mmHg',
    currentValue: '118/76 mmHg',
    trendDirection: 'stable',
    values: [
      { date: 'May 2026', value: 124 },
      { date: 'Jul 2026', value: 120 },
      { date: 'Sep 2026', value: 118 },
      { date: 'Oct 2026', value: 116 },
    ],
    flaggedForReview: false,
    aiInsight: 'Blood Pressure stable (Avg 118/76) across 3 visits. Lisinopril therapy is achieving targeted systolic < 120 mmHg.',
  },
  {
    id: 'trend-glucose',
    patientId: 'p-101',
    metricName: 'Fasting Blood Glucose',
    unit: 'mg/dL',
    currentValue: '91 mg/dL',
    trendDirection: 'stable',
    values: [
      { date: 'May 2026', value: 95 },
      { date: 'Jul 2026', value: 93 },
      { date: 'Sep 2026', value: 89 },
      { date: 'Oct 2026', value: 91 },
    ],
    flaggedForReview: false,
    aiInsight: 'Fasting glucose remains in optimal euglycemic zone (< 100 mg/dL).',
  },
  {
    id: 'trend-heart-rate',
    patientId: 'p-101',
    metricName: 'Resting Heart Rate',
    unit: 'bpm',
    currentValue: '68 bpm',
    trendDirection: 'improving',
    values: [
      { date: 'May 2026', value: 74 },
      { date: 'Jul 2026', value: 72 },
      { date: 'Sep 2026', value: 69 },
      { date: 'Oct 2026', value: 68 },
    ],
    flaggedForReview: false,
    aiInsight: 'Resting heart rate showing healthy downward trend corresponding with regular cardio activity.',
  },
];

export const INITIAL_ANOMALIES: AccessAnomalyAlert[] = [
  {
    id: 'alert-001',
    hospitalId: 'hosp-004',
    hospitalName: 'St. Jude Community Clinic',
    patientId: 'p-101',
    date: '2026-08-20',
    accessCount: 8,
    rollingAverage: 1.2,
    severity: 'high',
    abusePattern: 'Repeated Emergency Access Trigger on Expired Patient Consent',
    reason: 'Hospital attempted 8 emergency profile accesses within 4 hours without acute trauma verification code.',
    adminReviewed: false,
    timestamp: '2026-08-20T16:40:00Z',
  },
  {
    id: 'alert-002',
    hospitalId: 'suspicious-hosp-99',
    hospitalName: 'Shady Outpatient Center',
    patientId: 'p-101',
    date: '2026-08-22',
    accessCount: 4,
    rollingAverage: 0.5,
    severity: 'critical',
    abusePattern: 'Off-Hours Bulk Record Query Without Patient Token',
    reason: 'Multiple sequential EHR record requests made outside clinical operating window.',
    adminReviewed: false,
    timestamp: '2026-08-22T03:15:00Z',
  },
];

export const INITIAL_BLOCKS: BlockchainBlock[] = [
  {
    blockNumber: 48912,
    timestamp: '2026-10-24T10:14:02Z',
    previousHash: '0x71a2c984920381fa091283746182937461829374618293746182937461829374',
    merkleRoot: '0x4f8a9271c39048a1d7462bb1e892c9071b62391054a3',
    hash: '0x0000a891f7c29e1a8b9418293746182937461829374618293746182937461829',
    nonce: 849102,
    transactions: [INITIAL_ACCESS_EVENTS[0]],
  },
  {
    blockNumber: 48805,
    timestamp: '2026-10-22T15:30:19Z',
    previousHash: '0x6291a82371928374618293746182937461829374618293746182937461829374',
    merkleRoot: '0x8b12f491c981a44e7829103cba281744920418373e41',
    hash: '0x00003b8192a7c489201938471928374618293746182937461829374618293746',
    nonce: 194821,
    transactions: [INITIAL_ACCESS_EVENTS[1]],
  },
  {
    blockNumber: 45100,
    timestamp: '2026-07-12T02:15:00Z',
    previousHash: '0x5198273641829374618293746182937461829374618293746182937461829374',
    merkleRoot: '0x9d4a187263b190ca84729101238b17482910384799c2',
    hash: '0x0000f91823746182937461829374618293746182937461829374618293746182',
    nonce: 694012,
    transactions: [INITIAL_ACCESS_EVENTS[3]],
  },
];
